language: java

script:
- mvn -q -B -f pom.xml clean verify

deploy:
  provider: heroku
  api_key:
    secure: "e214f3dd-cc28-42d1-ba80-f74180e6ec54"
  app: mugues-spring-boot-docker
  on:
    repo: mugues/spring-boot-docker
