spring.main.allow-bean-definition-overriding: true
server:
  port: 8080
  servlet-path: /

management:
  port: 9001
  endpoints:
    web:
      exposure:
        include: "prometheus"
  security:
    enabled: false
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
