spring.main.allow-bean-definition-overriding: true
server:
  port: 8080
  servlet-path: /

management:
  port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false